docker-backend-repo: first-attempt-backend
docker-frontend-repo: first-attempt-frontend
infrastructure-code: thesis-app-infrastructure
backup-input-repo: thesis-backup-input-files
tier: backend
default-input-prod: false
default-input-release: false
default-input-feature: false
