name: WorkFlow-production

on:
  push:
    branches: 
      - 'master'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
          NS: 'prod'


    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check existence file.yaml 
      id: check_file
      uses: andstor/file-existence-action@v1
      with:
        files: "file.yaml, Dockerfile"
    - name: File not exists
      if: steps.check_file.outputs.files_exists == 'false'
      run: |
        echo "failed"
        exit 1
    - name: File exists
      if: steps.check_file.outputs.files_exists == 'true'
      run: echo "exists!"

    - name: Setup Python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.x"
    - run: pip install PyYAML
      name: Install py dependencies

    - run: python set-ns.py
      name: run set-namespace script 
    - run: python set-infr-params.py
  
 
  trigger-workflow:
    name: Trigger workflow
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: echo ::set-output name=ns::prod
        id: ns
      - run: echo "::set-outuput name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: branch
      - run:  echo  "${{ steps.branch.outputs.branch }}"
      - run:  echo  ${{ steps.branch.outputs.branch }}
      - run:  echo  "${ steps.branch.outputs.branch }"
      - name: Trigger infrastructure repo workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update-infrastructure-backend
          ref: master
          #inputs: '{"sha-tag" : "${{ github.sha }}", "code-branch" : "${{ steps.branch.outputs.branch }}","overlays-dir" : "${{steps.ns.outputs.ns}}" }'
          inputs: '{"sha-tag" : "${{ github.sha }}", "code-branch" : "master","overlays-dir" : "prod" }'
          repo: mattedamo/thesis-app-infrastructure
          token: ${{ secrets.TOKEN_GITHUB_DISPATCHER }}
