name: delete-branch

on:
  delete

jobs:
  
  trigger-workflow:
    name: Trigger workflow
    runs-on: ubuntu-latest
    if: contains(
          github.event.ref
          , 'features') ||
        contains(
          github.event.ref
          , 'releases')    
    steps:
      
      - name: Trigger infrastructure repo workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: delete-kustomize-dir
          ref: master
          inputs: '{"code-branch" : "${{ github.event.ref }}", "tier" : "${{secrets.TIER}}"}'
          repo: ${{ github.repository_owner }}/${{secrets.INFRASTRUCTURE_REPO}}
          token: ${{ secrets.PAT_TOKEN }}
